# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D2qkCW4T07xRrTUgMJtWUZoB_Splcbvm
"""

from fastapi import FastAPI
from pydantic import BaseModel
import pickle
import numpy as np  # ← ADD THIS

app = FastAPI()

class ModelInput(BaseModel):
    Pregnancies: int
    Glucose: int
    BloodPressure: int
    skinThickness: int
    Insulin: int
    BMI: float
    DiabetesPedigreeFunction: float
    Age: int

# Load model
diabetes_model = pickle.load(open('diabetes_model.sav', 'rb'))

@app.post('/diabetes_prediction')
def diabetes_pred(input_parameters: ModelInput):
    input_dict = input_parameters.dict()

    # Extract values in correct order
    input_list = [
        input_dict['Pregnancies'],
        input_dict['Glucose'],
        input_dict['BloodPressure'],
        input_dict['skinThickness'],
        input_dict['Insulin'],
        input_dict['BMI'],
        input_dict['DiabetesPedigreeFunction'],
        input_dict['Age']
    ]

    # ✅ CRITICAL FIX: Convert to 2D numpy array
    input_array = np.array(input_list).reshape(1, -1)

    # Make prediction
    prediction = diabetes_model.predict(input_array)

    if prediction[0] == 0:
        return {'prediction': 'The person is not diabetic'}
    else:
        return {'prediction': 'The person is diabetic'}






# ===== DEPLOYMENT SETTINGS =====
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
